# Exercício de Programação 1

<font color="red">**Prazo de submissão: 23:55 do dia 19/03/2020** </font>

2020.1 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel$\rightarrow$Restart e então execute **todas as células** (no menu, Cell$\rightarrow$Run All)
* Apenas o arquivo .ipynb deve ser submetido. Ele não deve ser compactado.
* Não deixe de preencher seu nome e número de matrícula na célula a seguir

Nome do aluno: Lucca Silva Medeiros

Matricula: 2019054773

## Parte 1: Python básico

In [15]:
# Exercício 1 - Imprima na tela os números de 1 a 10 e armazene-os em uma lista.
lista = [1,2,3,4,5,6,7,8,9,10]
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
# Exercício 2 - Crie duas strings e concatene as duas em uma terceira string
string1 = 'Lucca'
string2 = 'Silva'
string3 = string1+string2
print(string3)

LuccaSilva


In [17]:
# Exercício 3 - Crie uma tupla com os seguintes elementos: 1, 2, 2, 3, 4, 4, 4, 5 e depois utilize a função count do 
# objeto tupla para verificar quantas vezes o número 4 aparece na tupla
tupla = (1,2,2,3,4,4,4,5)
count = tupla.count(4)
print(count)

3


In [18]:
# Exercício 4 - Crie um dicionário com 3 chaves e 3 valores e imprima na tela
dicionario = {'Lucca' : 1, 'Silva' : 2, 'Medeiros' : 3}
print(dicionario)

{'Lucca': 1, 'Silva': 2, 'Medeiros': 3}


In [19]:
# Exercício 5 - Adicione mais um elemento ao dicionário criado no exercício anterior e imprima na tela
dicionario['Nome'] = 4
print(dicionario)

{'Lucca': 1, 'Silva': 2, 'Medeiros': 3, 'Nome': 4}


In [20]:
# Exercício 6 - Crie um novo dicionário invertendo o anterior (isto é, usando os valores como chave e vice-versa)
dicionarioinv = {1 : 'Lucca', 2 : 'Silva', 3 : 'Medeiros'}
print(dicionarioinv)

{1: 'Lucca', 2: 'Silva', 3: 'Medeiros'}


In [21]:
# Exercício 7 - Crie uma função que receba uma string como argumento e retorne a mesma string em letras maiúsculas.
# Faça uma chamada à função, passando como parâmetro uma string
def stringalta(string):
    return string.upper()

nome = 'lucca'
print(stringalta(nome))
    
    

LUCCA


In [22]:
# Exercício 8 - Crie uma função que receba como parâmetro uma lista de 4 elementos, adicione 2 elementos a lista e 
# imprima a lista. Esta função não deve retornar nada.
def ex8(lista):
    lista = lista + [100,101]
    print(lista)

lista = [1,2,3,4]
ex8(lista)
    
    

[1, 2, 3, 4, 100, 101]


In [23]:
# Exercício 9 - Faça a correção dos erros no código abaixo e execute o programa. Dica: são 3 erros.
temperatura = float(input('Qual a temperatura? '))
if temperatura > 30:
    print('Vista roupas leves.')
else:
    print('Busque seus casacos.')

Qual a temperatura? 40
Vista roupas leves.


In [24]:
# Exercício 10 - Crie uma função que conte quantas vezes a letra "r" aparece na frase abaixo. Use um placeholder (%) na 
# sua instrução de impressão

frase = "All models are wrong, but some are useful (George Box)"
def conta_r(_str):
    return _str.count('r')

print("Tem %.0f r's"% conta_r(frase))

    

Tem 4 r's


## Parte 2: numpy

## Questão 1

Crie as matrizes A, B e C abaixo e resolva as questões:
1. [ ] Calcule $(((A^T B)+B)C^{-1})$
2. [ ] Crie matrizes $\tilde A_{2x2}, \tilde B_{2x2}, \tilde C_{2x2}$, tal que sejam compostas pelo 2 primeiros elementos de cada linha das duas primeiras linhas. E repita a equação do item anterior.

**Dica** numpy.full, numpy.eye, numpy.ones e indexação de vetores.

$$
A = \begin{bmatrix}
 8 & 8 & 8\\
 8 & 8 & 8\\
 8 & 8 & 8
\end{bmatrix}_{3\times 3}
\qquad
B = \begin{bmatrix}
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1
\end{bmatrix}_{3\times 4}
\qquad
C = \begin{bmatrix}
 1 & 0 & 0 & 0 \\
 0 & 1 & 0 & 0 \\
 0 & 0 & 1 & 0 \\
 0 & 0 & 0 & 1
\end{bmatrix}_{4\times 4}
$$

In [25]:
import numpy as np
# Código para Exercício 1
A = np.array([[8,8,8],[8,8,8],[8,8,8]])
B = np.ones((3,4))
C = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

calculo1 = ((np.transpose(A).dot(B)) + B).dot(np.linalg.inv(C))

print(calculo1)

A2 = np.array([[8,8],[8,8]])
B2 = np.ones((2,2))
C2 = np.array([[1,0],[0,1]])

calculo2 = ((np.transpose(A2).dot(B2)) + B2).dot(np.linalg.inv(C2))

print(calculo2)


[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
[[17. 17.]
 [17. 17.]]


## Questão 2
**2A.** Escreva uma função python que recebe $m$ como entrada e executa os seguintes passos:
1. [ ] gera uma matriz aleatória $W_{m \times 4}$ (função **numpy.random.randn**),
2. [ ] divide cada uma das entradas por $\sqrt{m}$ (salva resultado em $\tilde W$),
3. [ ] calcula $Z = \tilde W^\top \times \tilde W$,
4. [ ] imprime $Z$,
5. [ ] calcula a norma Frobenius da diferença entre $Z$ e a matriz identidade $I_{4 \times 4}$.

In [26]:
# Código para Exercício 2

import math
import numpy as np

def questao2(m):
    W = np.random.randn(m,4)
    Wlinha = W/math.sqrt(m)
    Z = Wlinha.T@Wlinha
    print(Z)
    return np.linalg.norm(Z-np.eye(4),'fro')

print(questao2(10))


[[ 0.88854811 -0.26909822  0.12795725 -0.44128466]
 [-0.26909822  0.80163512  0.12757173 -0.05355625]
 [ 0.12795725  0.12757173  1.17320434 -0.11134056]
 [-0.44128466 -0.05355625 -0.11134056  0.94851824]]
0.8453031703226207


**2B.** Qual a norma da diferença obtida para $m=100$? E para $m=10000$?

In [27]:
diferenca1 = questao2(100)
diferenca2 = questao2(10000)
print("A diferença para m = 100 é {} e para m=10000 é {}".format(diferenca1,diferenca2))

[[ 1.16758227  0.01158619 -0.06148401 -0.08269556]
 [ 0.01158619  0.94559014  0.0742883   0.23359165]
 [-0.06148401  0.0742883   0.91142586  0.0413039 ]
 [-0.08269556  0.23359165  0.0413039   1.03842141]]
[[ 1.00629369 -0.01210606  0.00709256 -0.01361608]
 [-0.01210606  0.98715367 -0.00198994 -0.01114409]
 [ 0.00709256 -0.00198994  0.99972283  0.01134379]
 [-0.01361608 -0.01114409  0.01134379  1.00327633]]
A diferença para m = 100 é 0.43064096256999934 e para m=10000 é 0.03864752950429816


**2C.** O que podemos dizer sobre a matriz $\tilde W$?

Resposta: W linha é W normalizado.